# Archivo: .streamlit/secrets.toml

# --- Credenciales de Power BI API ---
POWERBI_USER = "admin@SanSilvestreAllende.onmicrosoft.com"
POWERBI_PASSWORD = "LewnAYYq5;."
POWERBI_TENANT_ID = "1fc53109-6a00-4a1f-a6bc-7ddfd4b3ddcf"
POWERBI_CLIENT_ID = "fe23a732-047e-45b8-b617-b34f6ac298a3"

# --- Usuarios del Portal de BI ---
[usuarios.admin]
contrasena = "CambiaEstaClaveSegura2026"
areas = ["Capital Humano", "Comercial", "Liquidaciones", "Operaciones", "Flotilla", "Códigos de Falla"]

[usuarios.operaciones1]
contrasena = "ClaveOperaciones2026"
areas = ["Operaciones"]

[usuarios.rh1]
contrasena = "ClaveRH2026"
areas = ["Capital Humano"]

[usuarios.liquidaciones1]
contrasena = "ClaveLiq2026"
areas = ["Liquidaciones"]
